sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
before_script:
  - npm prune
after_success:
  - npm run coverage
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
